%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Rafal\Documents\PW\6 semestr\PSZT\Projekt-1\DaneTest.xlsx
%    Worksheet: Arkusz1
%
% Auto-generated by MATLAB on 25-Mar-2020 21:46:04

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = "Arkusz1";
opts.DataRange = "A2:C9";

% Specify column names and types
opts.VariableNames = ["A", "B", "Weight"];
opts.VariableTypes = ["string", "string", "double"];
opts = setvaropts(opts, [1, 2], "EmptyFieldRule", "auto");

% Import the data
DaneTest = readtable("C:\Users\Rafal\Documents\PW\6 semestr\PSZT\Projekt-1\DaneTest.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts